### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by tbaraza** [tbaraza/vidly#7]
**Tasks**
- [ ] Create User model

- [ ] Create login controller

- [ ] Create login route

- [ ] Add tests for the login route
